### ISSUE TITLE
Minor bug in examples/torch/convex_approximate_dynamic_programming.ipynb

### ISSUE THREAD

**Issue by BenGravell** [cvxgrp/cvxpylayers#10]
I had to change the 3rd line in the "train" function from
q = torch.zeros((m, 1), requires_grad=True)
to
q = torch.zeros(m, 1).double().requires_grad_(True)
to avoid the error
"RuntimeError: Two or more parameters have different dtypes. Expected parameter 3 to have dtype torch.float64 but got dtype torch.float32."

**Comment by sbarratt** [comment]
Good point. Fixed in: https://github.com/cvxgrp/cvxpylayers/pull/11
