### ISSUE TITLE
Is it possible to implement a LeakyReLU?

### ISSUE THREAD

**Issue by ZikangZhou** [cvxgrp/cvxpylayers#106]
Hi,

Your work is really interesting! I notice you implement a ReLU layer using cvxpylayers. I wonder whether it is possible to implement a LeakyReLU using cvxpylayers? Thanks!

**Comment by bamos** [comment]
Yeah! One way to view that as an optimization problem is to change the constraint `y >=0` from the ReLU to `y >= negative_slope * x`:

```python
n = 100
negative_slope = 0.2

_x = cp.Parameter(n)
_y = cp.Variable(n)
obj = cp.Minimize(cp.sum_squares(_y-_x))
cons = [_y >= negative_slope*_x]
prob = cp.Problem(obj, cons)

layer = CvxpyLayer(prob, parameters=[_x], variables=[_y])

x = torch.linspace(-5, 5, steps=n, requires_grad=True)
y, = layer(x)
plt.plot(x.detach(), y.detach())
plt.xlabel('$x$')
plt.ylabel('$f(x)$')
```

This will produce:

![image](https://user-images.githubusercontent.com/707462/115973543-c99ed480-a523-11eb-9733-f92a324baa01.png)
