### ISSUE TITLE
Runing the example "ReLU Layers" encounts the following errors

### ISSUE THREAD

**Issue by JhoonUK** [cvxgrp/cvxpylayers#141]
ValueError                                Traceback (most recent call last)
Cell In[6], line 6
      4 l = torch.nn.MSELoss()(net(X), Y)
      5 print (l.item())
----> 6 l.backward()
      7 opt.step()

File D:\anaconda3\envs\pytorch\lib\site-packages\torch\_tensor.py:487, in Tensor.backward(self, gradient, retain_graph, create_graph, inputs)
    477 if has_torch_function_unary(self):
    478     return handle_torch_function(
    479         Tensor.backward,
    480         (self,),
   (...)
    485         inputs=inputs,
    486     )
--> 487 torch.autograd.backward(
    488     self, gradient, retain_graph, create_graph, inputs=inputs
    489 )

File D:\anaconda3\envs\pytorch\lib\site-packages\torch\autograd\__init__.py:197, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    192     retain_graph = create_graph
    194 # The reason we repeat same the comment below is that
    195 # some Python versions print out the first line of a multi-line function
    196 # calls in the traceback and some print out the last line
--> 197 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    198     tensors, grad_tensors_, retain_graph, create_graph, inputs,
    199     allow_unreachable=True, accumulate_grad=True)

File D:\anaconda3\envs\pytorch\lib\site-packages\torch\autograd\function.py:267, in BackwardCFunction.apply(self, *args)
    263     raise RuntimeError("Implementing both 'backward' and 'vjp' for a custom "
    264                        "Function is not allowed. You should only implement one "
    265                        "of them.")
    266 user_fn = vjp_fn if vjp_fn is not Function.vjp else backward_fn
--> 267 return user_fn(self, *args)

File D:\anaconda3\envs\pytorch\lib\site-packages\cvxpylayers\torch\cvxpylayer.py:344, in _CvxpyLayerFn.<locals>._CvxpyLayerFnFn.backward(ctx, *dvars)
    342 grad = [[] for _ in range(len(param_ids))]
    343 for i in range(ctx.batch_size):
--> 344     del_param_dict = compiler.apply_param_jac(
    345         dcs[i], -dAs[i], dbs[i])
    346     for j, pid in enumerate(param_ids):
    347         grad[j] += [to_torch(del_param_dict[pid],
    348                              ctx.dtype, ctx.device).unsqueeze(0)]

File D:\anaconda3\envs\pytorch\lib\site-packages\cvxpy\reductions\dcp2cone\cone_matrix_stuffing.py:208, in ParamConeProg.apply_param_jac(self, delc, delA, delb, active_params)
    200 """Multiplies by Jacobian of parameter mapping.
    201 
    202 Assumes delA is sparse.
   (...)
    205     A dictionary param.id -> dparam
    206 """
    207 if self.P is not None:
--> 208     raise ValueError("Can't apply Jacobian with a quadratic objective.")
    210 if active_params is None:
    211     active_params = {p.id for p in self.parameters}

ValueError: Can't apply Jacobian with a quadratic objective.

**Comment by bamos** [comment]
It looks like this issue is coming from CVXPY canonicalizing into a cone program with a quadratic objective by default now (with SCS 3.0 update). Unfortunately the  derivative with respect to the quadratic term isn't supported yet and I'm not sure of the best way of forcing CVXPY to canonicalize into the old SCS formatt with just a linear objective. This is a serious issue impacting some of my code using cvxpylayers too. One workaround for now is to downgrade to earlier versions of cvxpy/diffcp/scs that don't use the quadratic objective. @sbarratt @SteveDiamond @akshayka - are there any other patches for now that don't require downgrading?

**Comment by SteveDiamond** [comment]
@bamos you can change it back to the old canonicalization by setting the solver argument ``use_quad_obj = False``. Sorry this isn't more clearly documented. (Buried in here https://www.cvxpy.org/tutorial/advanced/index.html#setting-solver-options)

**Comment by bamos** [comment]
Thanks @SteveDiamond! I'll see if I can make that the default option in here
