### ISSUE TITLE
Examples are not working: ValueError: Can't apply Jacobian with a quadratic objective.

### ISSUE THREAD

**Issue by ib-proj** [cvxgrp/cvxpylayers#144]
I tried many examples in the folder examples and I get the error ValueError: Can't apply Jacobian with a quadratic objective. How can I fix the problem ?
@sbarratt 
@akshayka 
@bamos 

This is the last example I tried:
(https://github.com/cvxgrp/cvxpylayers/tree/master/examples/torch)/ReLU Layers.ipynb)

**Comment by itsmeyijie** [comment]
<img width="835" alt="image" src="https://user-images.githubusercontent.com/25410808/232205074-f47723c6-fab4-40ee-9e73-99089977c167.png">
same problem. And the answer seems incorrect. I just used the same code shown in the example.

**Comment by bamos** [comment]
Hi, there was an issue with how cvxpylayers was connected to SCS with the quadratic objective that I fixed last month in https://github.com/cvxgrp/cvxpylayers/commit/b2d46b08a3a9edf6715bca7afc1573802700d9fc. I think it's causing this issue. Can you try installing cvxpylayers from the latest version in this repo and confirm that it fixes it? This fix is not yet in the pip version of cvxpylayers -- @akshayka or @sbarratt, can you update the pip package?

**Comment by akshayka** [comment]
> Hi, there was an issue with how cvxpylayers was connected to SCS with the quadratic objective that I fixed last month in [b2d46b0](https://github.com/cvxgrp/cvxpylayers/commit/b2d46b08a3a9edf6715bca7afc1573802700d9fc). I think it's causing this issue. Can you try installing cvxpylayers from the latest version in this repo and confirm that it fixes it? This fix is not yet in the pip version of cvxpylayers -- @akshayka or @sbarratt, can you update the pip package?

Done!

@bamos , do you have a PyPI account? I can add you as a maintainer

**Comment by bamos** [comment]
> @bamos , do you have a PyPI account? I can add you as a maintainer

Yeah, my handle there is also `bamos`

**Comment by ib-proj** [comment]
It's now working, thank you for the help !
