### ISSUE TITLE
Broadcasting

### ISSUE THREAD

**Issue by bamos** [cvxgrp/cvxpylayers#2]
```python3
import cvxpy as cp
import torch 
from cvxpylayers.torch import CvxpyLayer

n, m = 2, 3
x = cp.Variable(n)
A = cp.Parameter((m, n))
b = cp.Parameter(m)
constraints = [x >= 0]
objective = cp.Minimize(0.5 * cp.pnorm(A @ x - b, p=1))
problem = cp.Problem(objective, constraints)
assert problem.is_dpp()

cvxpylayer = CvxpyLayer(problem, parameters=[A, b], variables=[x])
n_batch = 128
A_tch = torch.randn(m, n, requires_grad=True)
b_tch = torch.randn(n_batch, m, requires_grad=True)

# solve the problem
solution, = cvxpylayer(A_tch, b_tch)

# compute the gradient of the sum of the solution with respect to A, b
solution.sum().backward()
```

## Current output
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-a44521ae7231> in <module>
     14 
     15 # solve the problem
---> 16 solution, = cvxpylayer(A_tch, b_tch)
     17 
     18 # compute the gradient of the sum of the solution with respect to A, b

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    543             result = self._slow_forward(*input, **kwargs)
    544         else:
--> 545             result = self.forward(*input, **kwargs)
    546         for hook in self._forward_hooks.values():
    547             hook_result = hook(self, input, result)

~/anaconda3/lib/python3.7/site-packages/cvxpylayers-0.1.0-py3.7.egg/cvxpylayers/torch/cvxpylayer.py in forward(self, solver_args, *params)
    116             info=info,
    117         )
--> 118         sol = f(*params)
    119         self.info = info
    120         return sol

~/anaconda3/lib/python3.7/site-packages/cvxpylayers-0.1.0-py3.7.egg/cvxpylayers/torch/cvxpylayer.py in forward(ctx, *params)
    189                                 i, len(
    190                                     param_order[i].shape), len(
--> 191                                     p.shape)))
    192 
    193                     if not np.all(p.shape == param_order[i].shape):

RuntimeError: Inconsistent batch size passed in. Expected parameter 1 to have batch shape of 1 dims but got 2 dims.
```

**Comment by sbarratt** [comment]
I'm not sure what you mean here. Do you mean that we should infer that A_tch should be used for each b_tch?

**Comment by bamos** [comment]
Yes, and more generally if any of the inputs are batched, then we should check to make sure they all have the same number of examples, and then appropriately repeat the non-batched ones.

**Comment by sbarratt** [comment]
I definitely agree with checking they all have the same number of examples,
but I’m not sure about inferring the batch size. This might lead to silent
errors.

**Comment by bamos** [comment]
Hmm, what kind of silent errors do you have in mind? I'd really like to have this sugar (or something like it) for using the batched output from the previous layer with non-batched versions of the other parameters without manually having to re-shape all of them. This comes up a lot and is a useful feature that I was also able to put in qpth without (as far as I'm aware) any silent errors

**Comment by luzai** [comment]
Hi, thank you very much for this great tool! May I ask how to estimate the theoretical time complexity of cvxpylayers, for example, for a batched least square problem, how should time complexity related to number of input/output features $n$/$m$, batch size $bs$? 
``` python
import cvxpy as cp
import torch 
from cvxpylayers.torch import CvxpyLayer

n, m = 512, 10
bs=32
x = cp.Variable((n,bs))
A = cp.Parameter((m,n))
y = cp.Parameter((m,bs))
constraints = [x >= 0]
objective = cp.Minimize(0.5 * cp.pnorm(A @ x - y, p=2)) # -_x.T*_y - cp.sum(cp.entr(_y)) 
problem = cp.Problem(objective, constraints)
assert problem.is_dpp()

import time
tic=time.time()
cvxpylayer = CvxpyLayer(problem, parameters=[A, y], variables=[x])
time.time()-tic

A_tch = torch.randn(m, n, requires_grad=True).cuda()
y_tch = torch.randn(m,bs, requires_grad=False).cuda()

tic=time.time()
# solve the problem
solution, = cvxpylayer(A_tch,y_tch)

# compute the gradient of the sum of the solution with respect to A, b
s=solution.sum()
s.backward()
time.time()-tic, s
```

**Comment by bamos** [comment]
Hi @luzai - thanks! The scalability is very dependent on your problem and hardware setup. When I want to get a sense of this I just run experiments similar to the code snippet you sent in that vary the parameters, maybe others have more sophisticated intuitions here.

Also for any other questions you have can you file a separate issue or email us -- this specific issue is for tracking the development and discussions behind automatic repeating/reshaping for when a batch

**Comment by sbarratt** [comment]
@luzai Also, I will add that for a least squares problem, you are probably much better off implementing the solution (and its derivative) directly, since both have analytical expressions. You should use our package for more exotic problems, for example, non-negative least squares.

For a direct implementation of least squares, you could use a least squares PyTorch layer I wrote with analytical derivatives: https://github.com/sbarratt/lsat/blob/master/lstsq.py.

**Comment by akshayka** [comment]
@bamos , I can add this to the TF layer (unless you want to do it yourself)

**Comment by bamos** [comment]
> @bamos , I can add this to the TF layer (unless you want to do it yourself)

Sounds good -- you can take the lock on this for the TF layer

**Comment by bamos** [comment]
Resolved
