### ISSUE TITLE
Does it support sparse optimization?

### ISSUE THREAD

**Issue by bolimath** [cvxgrp/cvxpylayers#25]
Does the toolbox support differentiable optimization with big sparse matrix ?

**Comment by akshayka** [comment]
@bolimath , sorry for the late response. We currently do not yet support sparse tensor inputs. Support for sparse tensors is definitely on the roadmap. I believe TensorFlow has some limited support for sparse tensors, and PyTorch may have some as well.

In the meantime, if you are comfortable with calling a solver directly, our package diffcp (https://github.com/cvxgrp/diffcp) supports (large) sparse matrices.
