### ISSUE TITLE
softmax example

### ISSUE THREAD

**Issue by JunMa11** [cvxgrp/cvxpylayers#31]
Dear @bamos ,

Thanks for your quick reply.

I can't re-open the previous issue, so I create a new issue.

I have read the variational softmax implementation in the blog. In the blog, the input is a 1-dim vector.

>  I recommend formulating this so that the inputs to the cvxpylayer are always shaped as `[batch, n]`

I'm sorry that I don't get this point.

My input is `x.shape=[batch, class_channel, x, y, z]`. If I reshape it into `[batch, class_channel*x*y*z]`, the spatial information is broken. I still do not know how to deal with it in cvxpy.

Specifically, I do not know **how should I formulate the obj and cons with the 5D (shape=[batch, class_channel, x, y, z]) input tensor.**

```python
obj = cp.Minimize(-_x.T*_y - cp.sum(cp.entr(_y)))
cons = [np.ones(d, dtype=np.float32).T*_y == 1.]
```

Could you give me more guidance at your convenience?

Looking forward to your reply.

Kindest regards,
Jun

_Originally posted by @JunMa11 in https://github.com/cvxgrp/cvxpylayers/issues/29#issuecomment-557957628_

**Comment by sbarratt** [comment]
The softmax is separable over the batch and image dimensions. So you can
just use the softmax described in Brandon’s blog post that operates on a
vector of shape (classes,). Then before and after the layer, reshape the
input to [batch*x*y*z, classes] and then undo that after.

**Comment by JunMa11** [comment]
Dear @sbarratt ,

Thanks for your quick reply very much.
I try it now.
