### ISSUE TITLE
Required CXVPY version

### ISSUE THREAD

**Issue by sygi** [cvxgrp/cvxpylayers#34]
Hello,
thank you for providing this very useful library. I have some problems using it in my codebase, as it depends on an alpha version of CVXPY (1.1.a1).

Do you know if the functionalities introduced in CVXPY 1.1 are required for cxvpylayers? If not, is it possible to down the required version to the last stable one? Thank you!

**Comment by akshayka** [comment]
CVXPY 1.1 is in fact required for cvxpylayers. DPP and ASA form were introduced in 1.1, both of which cvxpylayers depends upon.
