### ISSUE TITLE
Infeasible soft constrained MPC problem 

### ISSUE THREAD

**Issue by sjcszw** [cvxgrp/cvxpylayers#36]
Hi,

I'm trying use cvxpylayers to train a model predictive control(MPC) layer. I use the slack variables so that it becomes a soft constrained MPC problem and is always feasible.
But by cvxpylayers sometimes it is infeasible.
Here is the code:

    import torch
    import cvxpy as cp
    from cvxpylayers.torch import CvxpyLayer

    def soft_MPC_layer(nu, nx, N, nineq_u, nineq_x):
        """Builds the MPC layer with soft constraints.

        The optimization problem is of the form
            \hat u,\hat x,\hat e  
                = argmin sum(i:0->N-1){ u(i)^T*R*u(i) +  x(i)^T*Q*x(i)
                + e(i)^T*E*e(i) } + x(N)^T*P*x(N) + e(N)^T*E*e(N)
                    subject to x(i+1) = A*x(i) + B*u(i), i=0,1,...,N-1
                               Hu*u(i) <= ku
                               Hx*x(i) <= kx+e(i)
                               e(i) >= 0
                               x(0) = x0

        where N is the number of MPC steps,
            R in S^{nu,nu},
            S^{,} is the set of all positive semi-definite matrices,
            Q, P in S^{nx, nx}
            E in S^{ne, ne}, where ne = nineq_x
            A in R^{nx, nx}
            B in R^{nx, nu}
            Hu in R^{nineq_u, nu}
            ku in R^{nineq_u}
            Hx in R^{nineq_x, nx}
            ku in R^{nineq_x}

        Take the matrix square-root of R, Q, E：mentioned in paper P19
        (Differentiable Convex Optimization Layers).
        """
        R_sqrt = cp.Parameter((nu, nu))
        Q_sqrt = cp.Parameter((nx, nx))
        P_sqrt = cp.Parameter((nx, nx))
        E_sqrt = cp.Parameter((nineq_x, nineq_x))
        A = cp.Parameter((nx, nx))
        B = cp.Parameter((nx, nu))
        Hu = cp.Parameter((nineq_u, nu))
        ku = cp.Parameter(nineq_u)
        Hx = cp.Parameter((nineq_x, nx))
        kx= cp.Parameter(nineq_x)
        x0 = cp.Parameter(nx)

        u = cp.Variable((nu, N))
        x = cp.Variable((nx, N+1))
        e = cp.Variable((nineq_x, N+1))

        obj = 0
        cons = []
        cons += [ x[:,0] == x0 ]
        for k in range(N):
            obj += cp.sum_squares(R_sqrt*u[:,k]) \
                    + cp.sum_squares(Q_sqrt*x[:,k]) \
                    + cp.sum_squares(E_sqrt*e[:,k])
            cons += [ x[:,k+1] == A@x[:,k] + B@u[:,k],
                Hu@u[:,k] <= ku,Hx@x[:,k] <= kx+e[:,k], e[:,k] >= 0 ]
        obj += cp.sum_squares(P_sqrt*x[:,N]) \
                + cp.sum_squares(E_sqrt*e[:,N])
        cons += [Hx@x[:,N] <= kx+e[:,N], e[:,N] >= 0 ]
        objs = cp.Minimize(obj)

        prob = cp. Problem(objs, cons)
        assert prob.is_dpp()

        layer = CvxpyLayer (prob, 
                            parameters =[R_sqrt, Q_sqrt, P_sqrt, E_sqrt,
                                         A, B, Hu, ku, Hx, kx, x0], 
                            variables =[  u, x, e ])
        return layer

    # Here is an infeasible example
    R_sqrt = torch.tensor([[0.1]])
    Q_sqrt = torch.tensor([[1., 0.],[0., 1.]])
    P_sqrt = torch.tensor([[24.9936,  1.8688],[ 1.8688,  1.4416]])
    E_sqrt = torch.tensor([[1., 0.],[0., 1.]])
    A = torch.tensor([[1.0000, 0.0500],[0.7500, 1.0000]])
    B = torch.tensor([[0.0000],[0.1500]])
    Hu = torch.tensor([[ 1.],[-1.]]) 
    ku = torch.tensor([2., 2.])
    Hx = torch.tensor([[ 0.,  1.],[ 0., -1.]]) 
    kx = torch.tensor([8., 8.])
    x0 = torch.tensor([-8.7417, -8.0000])

    layer = soft_MPC_layer(1 , 2, 5, 2, 2)
    u_opt, x_opt, e_opt, = layer(R_sqrt, Q_sqrt,
                              P_sqrt, E_sqrt,A, B,
                              Hu, ku, Hx, kx, x0) 

    # Change the x0 a little
    # It's solved but constraints are violated
    x0 = torch.tensor([-8.74, -8.0000])
    u_opt, x_opt, e_opt, = layer(R_sqrt, Q_sqrt,
                              P_sqrt, E_sqrt,A, B,
                              Hu, ku, Hx, kx, x0) 
    print(e_opt>=0)
    print(Hx*x_opt[:,5] <= kx+e_opt[:,5])

Many thanks,
Jicheng Shi

**Comment by bamos** [comment]
Hi -- thanks for reaching out! Glad you're finding this useful. I just took a quick look and it seems like this is coming from SCS not being able to solve your problem in the default iteration limit of 5k. You can enable the SCS verbose mode to see this happening, and can bump up the number of SCS iterations so the problem is properly solved by updating the call to the layer with:

```python3
u_opt, x_opt, e_opt, = layer(R_sqrt, Q_sqrt,
                          P_sqrt, E_sqrt,A, B,
                          Hu, ku, Hx, kx, x0, solver_args={'verbose': True, 'max_iters': 50000}) 
```

Also since this problem is a QP -- we're working on hooking up an OSQP backend and potentially other solvers that will significantly improve the performance. You can follow our progress (and potentially help out with this if you have some bandwidth) in https://github.com/cvxgrp/cvxpylayers/issues/28

Let us know if there's anything else for now!

-Brandon.

**Comment by bamos** [comment]
(also just sent in a PR so we print out a more useful recommendation for this issue in the future)

**Comment by sjcszw** [comment]
It works and thanks a lot!
