### ISSUE TITLE
Simpler examples

### ISSUE THREAD

**Issue by tom-adsfund** [cvxgrp/cvxpylayers#39]
The promise of mixing convex optimization and Pytorch/Tensorflow seems great, but most of the current examples in the repo are quite specific and elaborate.

I'd like to see more complete simple examples that highlight the simplest things you can do with mixing convex optimization and backprop.

The best example in the tutorial seems to be the LML layer, but there's no complete example of it in use. The polytope/ellipsoid examples aren't in complete practical examples.

I'd love to know how I can use these layers in real practical applications!

**Comment by bamos** [comment]
Hi, thanks for reaching out! We'll give some more thought to adding examples that give some more intuition on how to use these layers. I'll close this issue for now but let us know if you have any other thoughts.

**Comment by akshayka** [comment]
@tom-adsfund, you raise a fair point — we've been meaning to add simpler, more concrete examples to this repository, but haven't gotten around to it yet.

For applications to control, you might look to our recent paper, [Learning convex optimization control policies](https://arxiv.org/pdf/1912.09529.pdf). In that paper, we show how to use differentiable convex optimization layers to learn policies for portfolio optimization, autonomous driving, and supply chain optimization. The [source code](https://github.com/cvxgrp/cocp) for those applications uses cvxpylayers.

**Comment by tom-adsfund** [comment]
@akshayka Thanks! I skimmed through the paper, and unfortunately the examples are definitely too advanced for my purposes.

I look forward to if you can make simple examples for a regular ML guy!
