### ISSUE TITLE
is_dpp() missing?

### ISSUE THREAD

**Issue by finkga** [cvxgrp/cvxpylayers#42]
When instantiating a cvxplayer in the example notebook the call fails with the following _internal_ error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-217a0beea246> in <module>
----> 1 layer = CvxpyLayer(prob, parameters=[_x], variables=[_y])

/anaconda3/envs/torch1.x/lib/python3.6/site-packages/cvxpylayers/torch/cvxpylayer.py in __init__(self, problem, parameters, variables)
     68                      values returned from the forward pass.
     69         """
---> 70         if not problem.is_dpp():
     71             raise ValueError('Problem must be DPP.')
     72 

AttributeError: 'Problem' object has no attribute 'is_dpp'
```
This happens with a fresh install of cvxpylayers via pip:

```
$ pip install cvxpylayers
Processing ./Library/Caches/pip/wheels/a0/41/c1/ed7e505cbe573483e953f442039065d0b9a12f4fe11c14df88/cvxpylayers-0.1.2-cp36-none-any.whl
Requirement already satisfied: scipy>=1.1.0 in /anaconda3/envs/torch1.x/lib/python3.6/site-packages (from cvxpylayers) (1.1.0)
Requirement already satisfied: diffcp>=1.0.13 in /anaconda3/envs/torch1.x/lib/python3.6/site-packages (from cvxpylayers) (1.0.13)
Requirement already satisfied: numpy>=1.15 in /anaconda3/envs/torch1.x/lib/python3.6/site-packages (from cvxpylayers) (1.15.4)
Requirement already satisfied: cvxpy>=1.1.0a1 in /anaconda3/envs/torch1.x/lib/python3.6/site-packages (from cvxpylayers) (1.1.0a2)
Requirement already satisfied: threadpoolctl>=1.1 in /anaconda3/envs/torch1.x/lib/python3.6/site-packages (from diffcp>=1.0.13->cvxpylayers) (2.0.0)
Requirement already satisfied: scs>=2.0.2 in /anaconda3/envs/torch1.x/lib/python3.6/site-packages (from diffcp>=1.0.13->cvxpylayers) (2.0.2)
Requirement already satisfied: pybind11>=2.4 in /anaconda3/envs/torch1.x/lib/python3.6/site-packages (from diffcp>=1.0.13->cvxpylayers) (2.4.3)
Requirement already satisfied: ecos>=2 in /anaconda3/envs/torch1.x/lib/python3.6/site-packages (from cvxpy>=1.1.0a1->cvxpylayers) (2.0.7.post1)
Requirement already satisfied: osqp>=0.4.1 in /anaconda3/envs/torch1.x/lib/python3.6/site-packages (from cvxpy>=1.1.0a1->cvxpylayers) (0.6.1)
Requirement already satisfied: future in /anaconda3/envs/torch1.x/lib/python3.6/site-packages (from osqp>=0.4.1->cvxpy>=1.1.0a1->cvxpylayers) (0.18.2)
Installing collected packages: cvxpylayers
Successfully installed cvxpylayers-0.1.2
```
This happens on the following platform:

```
Darwin WE35261 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
```
The code (copied directly and unaltered from the supplied jupyter notebook) is:
```
import cvxpy as cp
from cvxpylayers.torch import CvxpyLayer

n = 201

_x = cp.Parameter(n)
_y = cp.Variable(n)
obj = cp.Minimize(cp.sum_squares(_y-_x))
cons = [_y >= 0]
prob = cp.Problem(obj, cons)

layer = CvxpyLayer(prob, parameters=[_x], variables=[_y])
```
I would be happy to be wrong about this problem, but I cannot see how my installation is different from other working installations locally.

**Comment by akshayka** [comment]
It looks like an older version of CVXPY (1.0.x) is being imported. You’ll need an alpha version of CVXPY (1.1.x) to use cvxpylayers (if you’re using pip to install packages, pip install --upgrade --pre cvxpy).

Can you print cp.__version__?

**Comment by finkga** [comment]
Thanks for responding. Looks like that is not the issue though. Here is a transcript:


$ ipython

Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46)

Type 'copyright', 'credits' or 'license' for more information

IPython 7.11.1 -- An enhanced Interactive Python. Type '?' for help.



In [1]: import cvxpy as cp



In [2]: cp.version

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-2-27d3783f40ed> in <module>

----> 1 cp.version



AttributeError: module 'cvxpy' has no attribute 'version'



In [3]: cp.__version__

Out[3]: '1.1.0a2'

Is the 1.1.0a2 alpha version the latest?

Thanks,

Glenn

**Comment by SteveDiamond** [comment]
Can you create a problem in that ipython shell and call ``problem.is_dpp()``? Might be pulling in different packages somehow.

**Comment by finkga** [comment]
Upgrading to the latest version via pip worked. Apparently anaconda is not up to date.  Thanks for your help.
