### ISSUE TITLE
ValueError: cannot reshape array of size -1390450388 into shape (1004, 'newshape')

### ISSUE THREAD

**Issue by urolyi1** [cvxgrp/cvxpylayers#45]
The following error occurs after constructing a cvxpylayer (on Windows). The same problem does not occur on macOS or Linux.

```
ValueError: cannot reshape array of size -1390450388 into shape (1004, 'newshape')
```

This may be an issue internal to cvx or one of the solvers on the backend. Looking at the stack trace one of the lines in the stack trace is
```
File "C:\Users\Uro\Anaconda3\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\conic_solver.py", line 271, in format_constraints
    reshaped_A = problem.A.reshape(restruct_mat.shape[1], -1, order='F').tocsr()
```
There is a comment mentioning a possible int overflow error when reshaping with scipy. Maybe this is related to the issue?

Here is an example of code that produces this problem (minus a large piece of data).

```python
central_S = ...
n_hos = 2
n_structures = central_S.shape[1]
n_h_t_combos = central_S.shape[0]
control_strength = 3.0


x1 = cp.Variable(n_structures)
s = cp.Parameter( (n_h_t_combos, n_structures) )  # valid structures
w = cp.Parameter(n_structures)  # structure weight
z = cp.Parameter(n_structures)  # control parameter
b = cp.Parameter(n_h_t_combos)  # max bid


constraints = [x1 >= 0, s @ x1 <= b]  # constraint for positive allocation and less than true bid
objective = cp.Maximize( (w.T @ x1) - control_strength * cp.norm(x1 - z, 2) )
problem = cp.Problem(objective, constraints)

l_prog_layer = CvxpyLayer(problem, parameters=[s, w, b, z], variables=[x1])
```

A running version of this code including the large `central_S` matrix is below.

https://gist.github.com/urolyi1/fe94153f7a872046f1f73274391f6c51

**Comment by akshayka** [comment]
Thanks for reporting! This is indeed an issue with CVXPY, specifically scipy.

Can you try upgrading your version of SciPy to the latest stable version?  I believe the overflow bug in reshaping sparse matrices was fixed in a recent version. If that doesn't fix it, we can open an issue on the CVXPY repository.

**Comment by urolyi1** [comment]
I was on scipy 1.4.1 when this happened. Let me know if there is anything else that could possibly help solve/find the bug.

**Comment by akshayka** [comment]
Thanks for reporting back! I've created an issue in the CVXPY repository (https://github.com/cvxgrp/cvxpy/issues/934).

(I'm closing this issue, not because it's resolved, but because it's a problem with CVXPY, not with this repository. )
