### ISSUE TITLE
Failed to build diffcp

### ISSUE THREAD

**Issue by camontblanc** [cvxgrp/cvxpylayers#63]
Hi! I've been having some trouble installing `cvxpylayers` using pip in Windows.

I have already done `pip install --upgrade pip` and it is in its latest version (20.1.1).
I also installed `conda install -c conda-forge cvxpy` and the error I am getting is `ERROR: Failed building wheel for diffcp`

Thank you very much.

**Comment by akshayka** [comment]
Can you post the entire output? You might need to install Visual C++ if you haven’t already https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by camontblanc** [comment]
Yes @akshayka you were totally right. I installed Visual C++ and everything is fine! Thank you once again.

**Comment by akshayka** [comment]
Great! You're welcome.
