### ISSUE TITLE
"_compute_once() got an unexpected keyword argument 'dpp'". 

### ISSUE THREAD

**Issue by amir9ume** [cvxgrp/cvxpylayers#71]
When I run the tutorial example given for pytorch, I get a value erro: got an unexpected keyword argument dpp. My cvxpy and cvxpylayers versions are '1.0.25' and '0.1.4'.

Code link to the tutorial : https://github.com/cvxgrp/cvxpylayers/blob/master/examples/torch/monotonic_output_regression.ipynb

**Comment by akshayka** [comment]
CVXPY Layers requires CVXPY v 1.1 or greater
