### ISSUE TITLE
parallelize operation

### ISSUE THREAD

**Issue by ZhaomingXie** [cvxgrp/cvxpylayers#72]
Hi, first of all thanks for the amazing library!

I have a question about whether the operation is parallelized when I feed batch data to the layer.

For example, I have a QP problem in the form min ||Ax-b||^2, with A size (n, m), b size (m), and I create a cvxlayer L that will take A, b as input.   

If generate A, b of size (num_batch, n, m), (num_batch, m), L(A, b) will give me an output of size (num_batch, n), however, the execution time increase linearly with num_batch. I wonder if this is the expected behavior? If so, is there anyway to make the operation parallelizable?

**Comment by ZhaomingXie** [comment]
After some investigation, I find that threading is implemented in diffcp. Strangely, if I set number of threads to 1, it is actually faster than the default (which is 12 on my machine).

**Comment by sbarratt** [comment]
It should be parallelizable. However, the canonicalization is still
single-threaded. There's a PR to make the canonlicalization batched:
https://github.com/cvxgrp/cvxpylayers/issues/53.
