### ISSUE TITLE
signal denoising example - new data

### ISSUE THREAD

**Issue by andrewcztrack** [cvxgrp/cvxpylayers#73]
Hi @akshayka @sbarratt  @SteveDiamond !!

Thank you for the amazing library. i am trying the signal denoising example with new data but i am getting an error

```python

import math

import cvxpy as cp
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from cvxpylayers.torch import CvxpyLayer

import latexify
latexify.latexify()

torch.set_default_tensor_type(torch.DoubleTensor)
%matplotlib inline


N_train=1000




test=yf.download("SPY", start="2012-01-01", end="2017-04-30")['Close'].to_numpy()
outputs=torch.from_numpy(test)
inputs=np.linspace(1,100,len(outputs))
inputs=torch.from_numpy(inputs)

X_train = inputs[:N_train]
Y_train = outputs[:N_train]

X_val = inputs[N_train:]
Y_val = outputs[N_train:]


len(X_val)
len(Y_val)

def create_layer():
   y_cp = cp.Variable(n)
   x_minus_y = cp.Variable(n)
   
   x_param = cp.Parameter(n)
   theta_param = cp.Parameter((n, n))
   lambda_param = cp.Parameter(pos=True)
   objective = (
       cp.sum_squares(theta_param @ x_minus_y) +
       lambda_param*cp.sum_squares(cp.diff(y_cp))
   )
   constraints = [
       x_minus_y == x_param - y_cp
   ]
   problem = cp.Problem(cp.Minimize(objective), constraints)
   layer = CvxpyLayer(
       problem,
       parameters=[x_param, theta_param, lambda_param],
       variables=[y_cp])
   return layer
   

layer = create_layer()

import torch
from torch.utils.data import TensorDataset, DataLoader
import numpy as np
from cvxpylayers.torch import CvxpyLayer

torch.set_default_dtype(torch.double)

from tqdm.notebook import tqdm


def fit(loss, params, X, Y, Xval, Yval, batch_size=128, lr=1e-3, epochs=100, verbose=False, print_every=1, callback=None):
   """

   Arguments:
       loss: given x and y in batched form, evaluates loss.
       params: list of parameters to optimize.
       X: input data, torch tensor.
       Y: output data, torch tensor.
       Xval: input validation data, torch tensor.
       Yval: output validation data, torch tensor.
   """

   train_dset = TensorDataset(X, Y)
   train_loader = DataLoader(train_dset, batch_size=batch_size, shuffle=True)
   opt = torch.optim.Adam(params, lr=lr)

   train_losses = []
   val_losses = []
   for epoch in tqdm(range(epochs)):
       if callback is not None:
           callback()
           
       with torch.no_grad():
           val_losses.append(loss(Xval, Yval).item())
       if verbose and epoch % print_every == 0:
           print("val loss %03d | %3.5f" % (epoch + 1, val_losses[-1]))

       batch = 1
       train_losses.append([])
       for Xbatch, Ybatch in train_loader:
           opt.zero_grad()
           l = loss(Xbatch, Ybatch)
           l.backward()
           opt.step()
           train_losses[-1].append(l.item())
           if verbose and epoch % print_every == 0:
               print("batch %03d / %03d | %3.5f" %
                     (batch, len(train_loader), np.mean(train_losses[-1])))
           batch += 1
   return val_losses, train_losses

theta_tch = torch.eye(n, requires_grad=True)
lambda_tch = torch.tensor(0.5, requires_grad=True)
params = [theta_tch, lambda_tch]

def loss_fn(X, actual):
   preds = layer(X, theta_tch, lambda_tch)[0]
   mse_per_example = (preds - actual).pow(2).mean(axis=1)
   return mse_per_example.mean()


val_losses, train_losses =  fit(
   loss_fn, params, X_train, Y_train, X_val, Y_val, lr=1e-2, batch_size=8,
   epochs=15, verbose=True, print_every=1)

```

with the above i am getting  -

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-58-0b0fb50d4406> in <module>
----> 1 val_losses, train_losses =  fit(
     2     loss_fn, params, X_train, Y_train, X_val, Y_val, lr=1e-2, batch_size=8,
     3     epochs=15, verbose=True, print_every=1)

<ipython-input-56-f19c59cb9b44> in fit(loss, params, X, Y, Xval, Yval, batch_size, lr, epochs, verbose, print_every, callback)
    32 
    33         with torch.no_grad():
---> 34             val_losses.append(loss(Xval, Yval).item())
    35         if verbose and epoch % print_every == 0:
    36             print("val loss %03d | %3.5f" % (epoch + 1, val_losses[-1]))

<ipython-input-57-0aead751c22d> in loss_fn(X, actual)
     4 
     5 def loss_fn(X, actual):
----> 6     preds = layer(X, theta_tch, lambda_tch)[0]
     7     mse_per_example = (preds - actual).pow(2).mean(axis=1)
     8     return mse_per_example.mean()

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   720             result = self._slow_forward(*input, **kwargs)
   721         else:
--> 722             result = self.forward(*input, **kwargs)
   723         for hook in itertools.chain(
   724                 _global_forward_hooks.values(),

~/cvxpylayers/cvxpylayers/torch/cvxpylayer.py in forward(self, solver_args, *params)
   150             info=info,
   151         )
--> 152         sol = f(*params)
   153         self.info = info
   154         return sol

~/cvxpylayers/cvxpylayers/torch/cvxpylayer.py in forward(ctx, *params)
   224                 p_shape = p.shape if batch_size == 0 else p.shape[1:]
   225                 if not np.all(p_shape == param_order[i].shape):
--> 226                     raise ValueError(
   227                         "Inconsistent parameter shapes passed in. "
   228                         "Expected parameter {} to have non-batched shape of "

ValueError: Inconsistent parameter shapes passed in. Expected parameter 0 to have non-batched shape of (100,) but got torch.Size([339]).
```

**Comment by andrewcztrack** [comment]
Essentially would like to use the signal example with some different series.
Cheers
Andrew

**Comment by andrewcztrack** [comment]
Hi All (@bamos, @akshayka @sbarratt @SteveDiamond  )

so i did get my code to run but now its coming up with an error.

import math

import cvxpy as cp
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from cvxpylayers.torch import CvxpyLayer

import latexify
latexify.latexify()

torch.set_default_tensor_type(torch.DoubleTensor)
%matplotlib inline


import yfinance as yf
data = yf.download("SPY", start="2008-01-01", end="2017-04-30")['Close']
xx=np.linspace(1,100,len(data))
dd=data.to_numpy()
s=int(np.ceil(len(dd)/100))

n=100
def strided_app(a, L, S ):  # Window len = L, Stride len/stepsize = S
    nrows = ((a.size-L)//S)+1
    n = a.strides[0]
    return np.lib.stride_tricks.as_strided(a, shape=(nrows,L), strides=(S*n,n))

ddd= strided_app(dd, 100, s)
xxx=strided_app(xx,100,s)



def f(x):
    # return math.sqrt(x)
    return torch.from_numpy(np.array(x))


ffxx=list(map(f, ddd))
xxxy=list(map(f, xxx))
y=torch.stack(ffxx)
x=torch.stack(xxxy)
x.shape()



N_train = 50

X_train = x[:N_train]
Y_train = y[:N_train]

X_val = x[N_train:]
Y_val = y[N_train:]
X_val.shape


def create_layer():
    y_cp = cp.Variable(n)
    x_minus_y = cp.Variable(n)
    
    x_param = cp.Parameter(n)
    theta_param = cp.Parameter((n, n))
    lambda_param = cp.Parameter(pos=True)
    objective = (
        cp.sum_squares(theta_param @ x_minus_y) +
        lambda_param*cp.sum_squares(cp.diff(y_cp))
    )
    constraints = [
        x_minus_y == x_param - y_cp
    ]
    problem = cp.Problem(cp.Minimize(objective), constraints)
    layer = CvxpyLayer(
        problem,
        parameters=[x_param, theta_param, lambda_param],
        variables=[y_cp])
    return layer
    

layer = create_layer()

**Comment by andrewcztrack** [comment]
import torch
from torch.utils.data import TensorDataset, DataLoader
import numpy as np
from cvxpylayers.torch import CvxpyLayer

torch.set_default_dtype(torch.double)

from tqdm.notebook import tqdm


def fit(loss, params, X, Y, Xval, Yval, batch_size=128, lr=1e-3, epochs=100, verbose=False, print_every=1, callback=None):
    """

    Arguments:
        loss: given x and y in batched form, evaluates loss.
        params: list of parameters to optimize.
        X: input data, torch tensor.
        Y: output data, torch tensor.
        Xval: input validation data, torch tensor.
        Yval: output validation data, torch tensor.
    """

    train_dset = TensorDataset(X, Y)
    train_loader = DataLoader(train_dset, batch_size=batch_size, shuffle=True)
    opt = torch.optim.Adam(params, lr=lr)

    train_losses = []
    val_losses = []
    for epoch in tqdm(range(epochs)):
        if callback is not None:
            callback()
            
        with torch.no_grad():
            val_losses.append(loss(Xval, Yval).item())
        if verbose and epoch % print_every == 0:
            print("val loss %03d | %3.5f" % (epoch + 1, val_losses[-1]))

        batch = 1
        train_losses.append([])
        for Xbatch, Ybatch in train_loader:
            opt.zero_grad()
            l = loss(Xbatch, Ybatch)
            l.backward()
            opt.step()
            train_losses[-1].append(l.item())
            if verbose and epoch % print_every == 0:
                print("batch %03d / %03d | %3.5f" %
                      (batch, len(train_loader), np.mean(train_losses[-1])))
            batch += 1
    return val_losses, train_losses


theta_tch = torch.eye(n, requires_grad=True)
lambda_tch = torch.tensor(0.5, requires_grad=True)
params = [theta_tch, lambda_tch]

def loss_fn(X, actual):
    preds = layer(X, theta_tch, lambda_tch)[0]
    mse_per_example = (preds - actual).pow(2).mean(axis=1)
    return mse_per_example.mean()

val_losses, train_losses =  fit(
    loss_fn, params, X_train, Y_train, X_val, Y_val, lr=1e-2, batch_size=64,
    epochs=200, verbose=True, print_every=1)

**Comment by andrewcztrack** [comment]
I get the following error

---------------------------------------------------------------------------
SolverError                               Traceback (most recent call last)
<ipython-input-50-5c9199ac00c0> in <module>
      8     return mse_per_example.mean()
      9 
---> 10 val_losses, train_losses =  fit(
     11     loss_fn, params, X_train, Y_train, X_val, Y_val, lr=1e-2, batch_size=64,
     12     epochs=200, verbose=True, print_every=1)

<ipython-input-48-f19c59cb9b44> in fit(loss, params, X, Y, Xval, Yval, batch_size, lr, epochs, verbose, print_every, callback)
     32 
     33         with torch.no_grad():
---> 34             val_losses.append(loss(Xval, Yval).item())
     35         if verbose and epoch % print_every == 0:
     36             print("val loss %03d | %3.5f" % (epoch + 1, val_losses[-1]))

<ipython-input-50-5c9199ac00c0> in loss_fn(X, actual)
      4 
      5 def loss_fn(X, actual):
----> 6     preds = layer(X, theta_tch, lambda_tch)[0]
      7     mse_per_example = (preds - actual).pow(2).mean(axis=1)
      8     return mse_per_example.mean()

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/cvxpylayers/cvxpylayers/torch/cvxpylayer.py in forward(self, solver_args, *params)
    150             info=info,
    151         )
--> 152         sol = f(*params)
    153         self.info = info
    154         return sol

~/cvxpylayers/cvxpylayers/torch/cvxpylayer.py in forward(ctx, *params)
    293                     "it is always solvable or increasing the number of "
    294                     "solver iterations.")
--> 295                 raise e
    296             info['solve_time'] = time.time() - start
    297 

~/cvxpylayers/cvxpylayers/torch/cvxpylayer.py in forward(ctx, *params)
    286             start = time.time()
    287             try:
--> 288                 xs, _, _, _, ctx.DT_batch = diffcp.solve_and_derivative_batch(
    289                     As, bs, cs, cone_dicts, **solver_args)
    290             except diffcp.SolverError as e:

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/diffcp/cone_program.py in solve_and_derivative_batch(As, bs, cs, cone_dicts, n_jobs_forward, n_jobs_backward, mode, warm_starts, **kwargs)
     91                     zip(As, bs, cs, cone_dicts, warm_starts)]
     92         with threadpool_limits(limits=1):
---> 93             results = pool.starmap(solve_and_derivative_wrapper, args)
     94         pool.close()
     95         xs = [r[0] for r in results]

~/miniconda3/envs/myenv1/lib/python3.8/multiprocessing/pool.py in starmap(self, func, iterable, chunksize)
    370         `func` and (a, b) becomes func(a, b).
    371         '''
--> 372         return self._map_async(func, iterable, starmapstar, chunksize).get()
    373 
    374     def starmap_async(self, func, iterable, chunksize=None, callback=None,

~/miniconda3/envs/myenv1/lib/python3.8/multiprocessing/pool.py in get(self, timeout)
    769             return self._value
    770         else:
--> 771             raise self._value
    772 
    773     def _set(self, i, obj):

~/miniconda3/envs/myenv1/lib/python3.8/multiprocessing/pool.py in worker(inqueue, outqueue, initializer, initargs, maxtasks, wrap_exception)
    123         job, i, func, args, kwds = task
    124         try:
--> 125             result = (True, func(*args, **kwds))
    126         except Exception as e:
    127             if wrap_exception and func is not _helper_reraises_exception:

~/miniconda3/envs/myenv1/lib/python3.8/multiprocessing/pool.py in starmapstar(args)
     49 
     50 def starmapstar(args):
---> 51     return list(itertools.starmap(args[0], args[1]))
     52 
     53 #

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/diffcp/cone_program.py in solve_and_derivative_wrapper(A, b, c, cone_dict, warm_start, mode, kwargs)
     26 def solve_and_derivative_wrapper(A, b, c, cone_dict, warm_start, mode, kwargs):
     27     """A wrapper around solve_and_derivative for the batch function."""
---> 28     return solve_and_derivative(
     29         A, b, c, cone_dict, warm_start=warm_start, mode=mode, **kwargs)
     30 

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/diffcp/cone_program.py in solve_and_derivative(A, b, c, cone_dict, warm_start, mode, **kwargs)
    209         SolverError: if the cone program is infeasible or unbounded.
    210     """
--> 211     result = solve_and_derivative_internal(
    212         A, b, c, cone_dict, warm_start=warm_start, mode=mode, **kwargs)
    213     x = result["x"]

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/diffcp/cone_program.py in solve_and_derivative_internal(A, b, c, cone_dict, warm_start, mode, raise_on_error, **kwargs)
    260     elif status != "Solved":
    261         if raise_on_error:
--> 262             raise SolverError("Solver scs returned status %s" % status)
    263         else:
    264             result["D"] = None

SolverError: Solver scs returned status Unbounded/Inaccurate

**Comment by sbarratt** [comment]
Can you post the full runnable code please? Sorry for the late response.

**Comment by andrewcztrack** [comment]
@sbarratt !! Hope your well! 
The code that i tried is above.
I am really just wondering how I would use this algorithm on a new nx1 data set. Kinds regards Andrews

**Comment by sbarratt** [comment]
Well it's impossible for your problem to be unbounded, so it's probably just an innacurate solve.
Try passing `layer(X, theta_tch, lambda_tch, solver_args={'eps': 1e-5, 'max_iters': 10_000})[0] and let me know if that works. Another thing that might help a lot is first scaling the dataset, so add the line `dd = (dd - dd.mean()) / dd.std()`.

**Comment by andrewcztrack** [comment]
Ah very interesting! Thank you @sbarratt. I will give it a try over the weekend.
Cheers,
Andrew

**Comment by sbarratt** [comment]
Just the first suggestion works for me!

Surely the scaling will help a lot too.

val loss 200 | 13938.88302
batch 001 / 001 | 8381.14242

Best,
Shane

**Comment by andrewcztrack** [comment]
Hi @sbarratt !! hope your well. do mean the below-

```python
def create_layer():
    y_cp = cp.Variable(n)
    x_minus_y = cp.Variable(n)
    solver_args={'eps': 1e-5, 'max_iters': 10_000} 
    
    x_param = cp.Parameter(n)
    theta_param = cp.Parameter((n, n))
    lambda_param = cp.Parameter(pos=True)
    objective = (
        cp.sum_squares(theta_param @ x_minus_y) +
        lambda_param*cp.sum_squares(cp.diff(y_cp))
    )
    constraints = [
        x_minus_y == x_param - y_cp
    ]
    problem = cp.Problem(cp.Minimize(objective), constraints)
    layer = CvxpyLayer(
        problem,
        parameters=[x_param, theta_param, lambda_param],
        variables=[y_cp])
    return layer
    
​
layer = create_layer()
```

When i try the above i get the below error.


```python

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/diffcp/cone_program.py in solve_and_derivative(A, b, c, cone_dict, warm_start, mode, **kwargs)
    209         SolverError: if the cone program is infeasible or unbounded.
    210     """
--> 211     result = solve_and_derivative_internal(
    212         A, b, c, cone_dict, warm_start=warm_start, mode=mode, **kwargs)
    213     x = result["x"]

~/miniconda3/envs/myenv1/lib/python3.8/site-packages/diffcp/cone_program.py in solve_and_derivative_internal(A, b, c, cone_dict, warm_start, mode, raise_on_error, **kwargs)
    260     elif status != "Solved":
    261         if raise_on_error:
--> 262             raise SolverError("Solver scs returned status %s" % status)
    263         else:
    264             result["D"] = None

SolverError: Solver scs returned status Unbounded/Inaccurate
```

**Comment by sbarratt** [comment]
Can you also add the argument verbose=True and add the solver output to
this issue?
