### ISSUE TITLE
How long "should" a forward pass take to run?

### ISSUE THREAD

**Issue by currymj** [cvxgrp/cvxpylayers#76]
We have a particular problem with 24 variables and 14 constraints. Running just the forward pass with a batch size of about 128 takes about 1/3 of a second -- this is on a laptop, but we see similar results on a node from our cluster.

Does this seem like a reasonable speed for running the forward pass? Any parameters we could try tweaking to speed it up?

During training, we've also run into "Unbounded/Inaccurate" errors, although these are hard to reproduce consistently. But it has us thinking that there might be something ill-conditioned about our problem, and that possibly preconditioning or some other trick could result in an equivalent problem that is easier for SCS to deal with.

[Here is a gist](https://gist.github.com/currymj/a74cf5a5887b363d697382c7ac35551f) that just defines the cvxpylayer and times 100 forward passes.

**Comment by akshayka** [comment]
To see how long it should take to solve the problem, I'd recommend solving a single instance using (vanilla) CVXPY, and solving with the `verbose=True` keyword argument to see how long the solver spends (ie, don't measure the time CVXPY spends canonicalizing the problem). Feel free to experiment with multiple solvers, such as SCS and ECOS.

Then, compare the time you measured with the time spent in the solver when solving a single instance of the problem via CVXPY Layers. The times should be similar (if they're not, we might have an issue we need to address). Next solve a batch of problems using CVXPY Layers, and calculate whether you've received the expected speed-up; once again if the speed-up is not as large as you expect, that might point to another thing we should look into.

If you report the timings you see, that will be helpful to us.

Sorry I don't have more specific feedback!

For your second question, yes, it's possible that your problem becomes ill-conditioned. Limited support for the ECOS solver was recently added (https://github.com/cvxgrp/cvxpylayers/issues/86, for a code sample). You might try using ECOS and see if that helps.
