### ISSUE TITLE
Parameter affine or Parameter free

### ISSUE THREAD

**Issue by SoumiDas** [cvxgrp/cvxpylayers#80]
Hi,
I would like to clarify one particular thing i.e if I have an expression: cp.multiply(cp.exp(X),Y) where X is a parameter affine expression, and Y is a parameter-free expression and cvxpy as cp , is this particular problem not a DPP? Does cp.exp(X) return a parameter-free value leading to violation of the conditions?

It will be really helpful if my doubt is cleared.
Thanks!

**Comment by sbarratt** [comment]
You should generally refrain from applying cvxpy atoms to parameters, and
instead perform the operation outside cvxpy. So you code would instead look
like:

‘’’
X_exp = cp.Parameter()
cp.multiply(X_exp, Y)
X_exp.value = np.exp(X)
‘’’

**Comment by cs60021SDM** [comment]
Thanks! However, the error I am currently encountering says " TypeError: loop of ufunc does not support argument 0 of type MulExpression which has no callable exp method". Any way to debug this error?

**Comment by SoumiDas** [comment]
Thanks! However, the error I am encountering says "TypeError: loop of ufunc does not support argument 0 of type MulExpression which has no callable exp method". Any way to debug this error?

**Comment by sbarratt** [comment]
Please include full working code

**Comment by SoumiDas** [comment]
`def checkatomlayer():
  X= cp.Parameter((2,2))
  X_exp = cp.Parameter((2,2))
  Y = cp.Variable((2,2))
  obj = cp.sum(cp.multiply(X_exp,Y))
  X_exp.value = np.exp(X)
  objective = cp.Minimize(obj)
  prob = cp.Problem(objective, [Y>=0.0,Y<=1.0])
  print("Solving")
  layer = CvxpyLayer(prob, parameters=[X], variables=[Y])
  return layer

layer = checkatomlayer()`

Compiling this block of code leads to the error "AttributeError: 'Parameter' object has no attribute 'exp'" followed by "TypeError: loop of ufunc does not support argument 0 of type Parameter which has no callable exp method".

**Comment by sbarratt** [comment]
Ah. Remove the line X_exp.value = np.exp(X), and use X exponential Ed when
you call layer.

**Comment by SoumiDas** [comment]
Thanks! But, if I have the following setup where I do not provide the variable directly but via some operation, then I am unsure how do I exactly call the exponential over it. It'll be really helpful if you can help me figure this out.

`class Layer(torch.nn.Module):
    def __init__(self, D_in, D_out, finc):
        super(Layer, self).__init__()
        self.theta = torch.nn.Parameter(torch.rand(D_out, D_out),requires_grad=True)

        theta = cp.Parameter((D_out, D_out))
        sub_exp = cp.Parameter((D_in, D_in))
        Zn = cp.Variable((D_in, D_in))

        obj = cp.sum(cp.multiply(sub_exp,Zn)) #\sum (e^{(M.theta.M^T)}.Z) where M is a torch array, theta is a parameter, Z is the output variable.

        sub_exp = np.exp((finc@theta)@finc.T) #(M.theta.M^T)

        constraints = [0 <= Zn, Zn <= 1]
        objective = cp.Minimize(obj)
        prob = cp.Problem(objective, constraints)
        print("Solving")
        self.layer = CvxpyLayer(prob, parameters=[theta], variables=[Zn])
        
    def forward(self):
        return self.layer(self.theta)[0]

finc = torch.randn((20,50))
layer = Layer(20,50,finc)`

Running this leads to the errors: "AttributeError: 'MulExpression' object has no attribute 'exp' " followed by "TypeError: loop of ufunc does not support argument 0 of type MulExpression which has no callable exp method".

**Comment by SoumiDas** [comment]
Thanks! But, if I have the following setup where I do not provide the variable directly but via some operation, then I am unsure how do I exactly call the exponential over it. It'll be really helpful if you can help me figure this out.

`class Layer(torch.nn.Module):
    def init(self, D_in, D_out, finc):
       super(Layer, self).init()
       self.theta = torch.nn.Parameter(torch.rand(D_out, D_out),requires_grad=True)
 
       theta = cp.Parameter((D_out, D_out))
       sub_exp = cp.Parameter((D_in, D_in))
       Zn = cp.Variable((D_in, D_in))

       obj = cp.sum(cp.multiply(sub_exp,Zn)) #\sum (e^{(M.theta.M^T)}.Z) where M is a torch array, theta is a parameter, Z is the output variable.

       sub_exp = np.exp((finc@theta)@finc.T) #(M.theta.M^T)
 
        constraints = [0 <= Zn, Zn <= 1]
        objective = cp.Minimize(obj)
        prob = cp.Problem(objective, constraints)
        print("Solving")
        self.layer = CvxpyLayer(prob, parameters=[theta], variables=[Zn])
    
   def forward(self):
        return self.layer(self.theta)[0]

finc = torch.randn((20,50))
layer = Layer(20,50,finc)`

Running this leads to the errors: "AttributeError: 'MulExpression' object has no attribute 'exp' " followed by "TypeError: loop of ufunc does not support argument 0 of type MulExpression which has no callable exp method".

**Comment by sbarratt** [comment]
You can’t call cvxpy atoms on numpy or torch arrays.

**Comment by SoumiDas** [comment]
I mean "where I do not provide the parameter* directly but via some operation".

**Comment by sbarratt** [comment]
You cannot assign parameters to values. You must pass them as arguments to
the layer.

**Comment by SoumiDas** [comment]
Ok thanks! Just one query i.e
cp.sum(cp.multiply(((finc@theta)@finc.T),Z)) where Z is variable, theta is parameter, even though follows DPP,

 if I put cp.exp before ((finc@theta)@finc.T) leading to cp.sum(cp.multiply(cp.exp((finc@theta)@finc.T),Z)) it fails to being a DPP. Is it because cp.exp over that expression leads to a parameter free expression?

**Comment by akshayka** [comment]
No, not quite.

cp.exp(finc @ theta) @ finc.T is not affine in its parameters (Z).

Z is a variable (not parameter-free).

"Under DPP, the product of two expressions is affine when at least one of the expressions is constant, or when one of the expressions is parameter-affine and the other is parameter-free."

This condition is not met (the left hand side is not parameter affine but the right hand side is parameter free).

Therefore the product is not DPP.

In your case, why not do the exp outside CVXPY? Remove the exp, and remove finc from your CVXPY program. Write cp.multiply(theta, Z) in CVXPY. Before solving, set Z.value to np.exp(finc @ theta_np) @ finc.T.

For this to work, finc and theta_np must be numpy arrays. (Or if you're using PyTorch replace numpy with torch).

(Quote from the CVXPY tutorial: https://www.cvxpy.org/tutorial/advanced/index.html#disciplined-parametrized-programming)

**Comment by SoumiDas** [comment]
Okay thanks got it! 

So, if I would want the output of cvxpylayers involving the above particular problem from varying 'finc' across batches, it won't be possible for me to feed it as an input to the cvxpylayers object since cvxpylayers accept parameters as its argument. If I create a constructor with these numpy arrays as arguments (since finc changes with batches), I would have to create its object everytime with a new batch. 

Please correct me if I have made any mistake in saying this.
