### ISSUE TITLE
How to choose solver for CvxpyLayer

### ISSUE THREAD

**Issue by blenderben2** [cvxgrp/cvxpylayers#81]
Is it possible to choose a solver for `CvxpyLayer`? I suspect `solver_args` has it, but it is hard to find all the valid keys for it.

I tried `cvxpylayer(..., solver_args={'solver': 'SCS'})` and returns:

> 'solver' is an invalid keyword argument for this function

**Comment by SoumiDas** [comment]
Hi,
Yes, I think it is possible to choose a solver for CvxpyLayer. However, the parameter 'solver_args' needs to have the keyword arguments as one of its keys. So, in this case, the key will be 'solve_method'. The respective keys can be found under diffcp module. The following sample code will probably make it more clear:

`a = cp.Parameter(3)
b = cp.Variable(3)
obj = cp.sum(cp.sum_squares(a-b))
objec = cp.Minimize(obj)
prob = cp.Problem(objec, [b>=0])
layer = CvxpyLayer(prob, parameters=[a], variables=[b])

a1 = torch.ones(3)
b1 = torch.eye(3)
layer(a1, solver_args={'solve_method':'ECOS'})`

Hope it helps!

**Comment by blenderben2** [comment]
yes this helps thanks !
