### ISSUE TITLE
[Question/Documentation] Batch Convex Problems

### ISSUE THREAD

**Issue by Taha-Bahadori** [cvxgrp/cvxpylayers#91]
Is there any example showing how to solve a batch of convex problems using `cvxpylayers`?

**Comment by sbarratt** [comment]
In most of our examples we solve a batch of problems.

Eg: https://github.com/cvxgrp/cvxpylayers/blob/master/examples/torch/ReLU%20Layers.ipynb

Here the batch size is 300.

**Comment by Taha-Bahadori** [comment]
@sbarratt Sorry for stupid question, I did look at the ReLU example. I am solving a log_sum_exp minimization problem of the form `log_sum_exp(Ax+b)`. I have written the following piece:
```python
def get_layer(m, n):
    x = cp.Variable(n)
    A = cp.Parameter((m, n))
    b = cp.Parameter(m)
    objective = cp.Minimize(cp.log_sum_exp(A @ x + b, axis=0))
    problem = cp.Problem(objective)
    return CvxpyLayer(problem, [A, b], [x])
```

When I pass the `A` in batch size of `(bsize, m, n)`, I get the following error:
```
*** ValueError: Invalid parameter size passed in.
Expected parameter 1 to have have 1 or 2 dimensions but got 3 dimensions
```
Can you help with my example?

**Comment by sbarratt** [comment]
The following code works for me: (I had to add the constraints -1 <= x <= 1
to make the problem bounded for some reason...)

```python
import torch
import cvxpy as cp
from cvxpylayers.torch import CvxpyLayer

batch_size = 32
m = 20
n = 10

x = cp.Variable(n)
A = cp.Parameter((m, n))
b = cp.Parameter(m)
objective = cp.Minimize(cp.log_sum_exp(A @ x + b, axis=0))
problem = cp.Problem(objective, [x >= -1, x <= 1])

layer = CvxpyLayer(problem, [A, b], [x])

Atch = torch.randn(batch_size, m, n)
btch = torch.randn(batch_size, m)

x = layer(Atch, btch)[0]

print(x)
```

**Comment by sbarratt** [comment]
The following code works for me: (I had to add the constraints -1 <= x <= 1
to make the problem bounded for some reason...)

```
import torch
import cvxpy as cp
from cvxpylayers.torch import CvxpyLayer

batch_size = 32
m = 20
n = 10

x = cp.Variable(n)
A = cp.Parameter((m, n))
b = cp.Parameter(m)
objective = cp.Minimize(cp.log_sum_exp(A @ x + b, axis=0))
problem = cp.Problem(objective, [x >= -1, x <= 1])

layer = CvxpyLayer(problem, [A, b], [x])

Atch = torch.randn(batch_size, m, n)
btch = torch.randn(batch_size, m)

x = layer(Atch, btch)[0]

print(x)
```
Let me know if this solves the problem and I can close the issue.

**Comment by Taha-Bahadori** [comment]
Thank you. It was a stupid mistake. My `b` variable was in the shape of `(bsize, m, 1)` instead of `(bsize, m)`.

**Comment by sbarratt** [comment]
No worries; I make countless mistakes like this every day.

**Comment by Taha-Bahadori** [comment]
@sbarratt I have encountered a weird issue: my neural network that uses the above layer with only `n=11` gets stuck in forward step of the cvxlayer. Strangely, when I debug using `pdb`, it goes forward as I step over. This phenomenon happens on two Ubuntu servers, but does not happen on my Mac laptop (the code loops properly). I tried both pytorch-lightning and my custom pytorch training codes. 

Is it possible to enable verbosity for debugging purposes? Do you know why that phenomenon may happen?

**Comment by akshayka** [comment]
That sounds like a deadlock. If you solve single problems, instead of batching, does the layer still hang?

**Comment by Taha-Bahadori** [comment]
@akshayka I have fixed the batching typo as we discussed before. 

I created a `for` loop to solve single problems, per your suggestion. It works now but it is super slow. It takes 5 minutes to solve a problem with only `9` variables!

**Comment by Taha-Bahadori** [comment]
@akshayka @sbarratt I found out that the source of issue was that in my Linux server the computational packages were not properly installed. I installed a new environment using conda and now the algorithm runs with a reasonable speed. Thank you for your responses.
