### ISSUE TITLE
Major differences compared to CVXPY

### ISSUE THREAD

**Issue by Taha-Bahadori** [cvxgrp/cvxpylayers#93]
I am trying to solve a log-sum-exp problem with cvxpylayers. But the results are significantly different from the solution by cvxpy. I have provided [the data file here](https://drive.google.com/file/d/1CmlHy4Gh2k8oURLAEnWKNFVD-zOwQBLi/view?usp=sharing).

Here is the test code:
```python
import torch
import cvxpy as cp
from cvxpylayers.torch import CvxpyLayer

def lse_layer(m=1000, n=9):
    x = cp.Variable(n)
    A = cp.Parameter((m, n))
    b = cp.Parameter(m)
    objective = cp.Minimize(cp.log_sum_exp(A @ x + b, axis=0)+1e-4*cp.norm1(x))
    problem = cp.Problem(objective)
    return CvxpyLayer(problem, [A, b], [x])

def cvxpy_sol(A, b):
    A = A.detach().numpy()
    b = b.detach().numpy()
    x = cp.Variable(A.shape[1])
    objective = cp.Minimize(cp.log_sum_exp(A @ x + b, axis=0)+1e-4*cp.norm1(x))
    problem = cp.Problem(objective)
    problem.solve()
    return torch.from_numpy(x.value)


A, b = torch.load('test_data.trc')

print('CVXPY Solution:')
print(cvxpy_sol(A, b))

print('Layer Solution:')
layer = lse_layer()
print(layer(A, b)[0])
```

The following results shows that the solutions are significantly different. My other tests show that CVXPY solution is correct. Can you help me to use the cvxpylayer correctly to get the same solution that CVXPY gets?

```
CVXPY Solution:
tensor([ 4.0779e-03, -1.2261e-01,  5.4994e-02, -1.9269e-01,  1.4758e-01,
         1.4542e+01, -8.2787e+00, -1.5027e+01, -1.3752e+01],
       dtype=torch.float64)
Layer Solution:
/Users/bahadorm/miniconda3/lib/python3.7/site-packages/diffcp/cone_program.py:282: UserWarning: Solved/Inaccurate.
  warnings.warn("Solved/Inaccurate.")
tensor([-0.0264, -0.0650,  0.1088, -0.0316,  0.0167,  4.8961, -3.1628, -5.5888,
        -5.4104], grad_fn=<_CvxpyLayerFnFnBackward>)
```

Trying to use `solver_args={"solve_method": "ECOS"}`, results in `NotImplementedError: Exponential cones not supported yet.` I want to see how I should use the `SCS` solver properly.

**Comment by Taha-Bahadori** [comment]
I read https://github.com/cvxgrp/diffcp/issues/31 and realized that just by increasing the value of the penalization parameter, the solutions become much closer. For now, this solves the problem. But I will wait for the support of ECOS solver.

**Comment by sbarratt** [comment]
Yes, the solution is to add `eps` and `acceleration_lookback` arguments as follows:
```
layer(A, b, solver_args={"eps": 1e-8, "acceleration_lookback": 0})
```

I tried running your code with randomly generated data, and found the iterates diverging; disabling acceleration_lookback helps a lot. In fact we do it in almost all of our experiments.

**Comment by Taha-Bahadori** [comment]
@sbarratt Thank you. I wish you could add these tips to the documentation.

BTW, I think the algorithm's runtime does not reduce when I use `torch.no_grad()`.

**Comment by akshayka** [comment]
> Yes, the solution is to add `eps` and `acceleration_lookback` arguments as follows:
> 
> ```
> 
> layer(A, b, solver_args={"eps": 1e-8, "acceleration_lookback": 0})
> 
> ```
> 
> 
> 
> I tried running your code with randomly generated data, and found the iterates diverging; disabling acceleration_lookback helps a lot. In fact we do it in almost all of our experiments.

For some reason I thought we did this by default. Should we make no AA the default?

**Comment by Taha-Bahadori** [comment]
@sbarratt @akshayka 
When I used these flags, I got much worse results, though it was much faster. I have to remove these flags.
