### ISSUE TITLE
[Documentation] Document how to use ECOS

### ISSUE THREAD

**Issue by akshayka** [cvxgrp/cvxpylayers#97]
We get lots of questions about other solvers, and SCS's unreliability, and we usually tell people they can try ECOS instead.

We should add a bit of documentation to the README that explains how to use ECOS.

**Comment by akshayka** [comment]
Duplicate of #90. I'll close 90.

**Comment by sbarratt** [comment]
https://github.com/cvxgrp/cvxpylayers/pull/98
